### ISSUE TITLE
Issues with the SCC Taiko Drums sfz

### ISSUE THREAD

**Issue by arakash92** [davem2/sfz2bitwig#1]
Just wanted to alert you that this Taiko Drum sfz isn't being converted correctly. It's a popular SFZ file afaik.

```python
Traceback (most recent call last):
  File "/home/arakash/scripts/sfz2bitwig/sfz2bitwig.py", line 459, in <module>
    main()
  File "/home/arakash/scripts/sfz2bitwig/sfz2bitwig.py", line 39, in main
    multisamp.initFromSFZ(fn,args.noloop)
  File "/home/arakash/scripts/sfz2bitwig/sfz2bitwig.py", line 143, in initFromSFZ
    newsample['sample-stop'] = self.getsamplecount(newsampleFullPath)
  File "/home/arakash/scripts/sfz2bitwig/sfz2bitwig.py", line 304, in getsamplecount
    ifile = wave.open(path)
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "/usr/lib/python2.7/wave.py", line 274, in _read_fmt_chunk
    raise Error, 'unknown format: %r' % (wFormatTag,)
wave.Error: unknown format: 3
```

Also, thanks a ton for this tool!

**Comment by davem2** [comment]
Hey, thanks for the report. 

I downloaded version 1.0 of SCC Taiko Drums from [here](http://www.schristiancollins.com/vi-percussion.php) and was able to convert that one without error.

Is that the same version of the SCC Taiko Drums you're using? What OS are you using? 

Running with the --noloop option should get around the error for now (though you wont get the loop for Taiko C5.wav)

**Comment by MMulthaupt** [comment]
Not sure if this helps, but I get the following output:

```
D:\Temp\sfz2bitwig>python --version
Python 3.7.4

D:\Temp\sfz2bitwig>python sfz2bitwig.py "D:\Vault\Samples\SCC Taiko Drums\SCC Taiko Drums.sfz"

Converting D:\Vault\Samples\SCC Taiko Drums\SCC Taiko Drums.sfz to multisample
WARNING: Skipping duplicate sample: Taiko Drum 5-3.wav (D:\Vault\Samples\SCC Taiko Drums\Samples\Taiko Drum 5-3.wav)
Extracted loop point (8,45687) from Samples\Taiko C5.wav
Extracted loop point (8,45687) from Samples\Taiko C5.wav
WARNING: Skipping duplicate sample: Taiko C5.wav (D:\Vault\Samples\SCC Taiko Drums\Samples\Taiko C5.wav)
WARNING: Skipping duplicate sample: taiko1-p.wav (D:\Vault\Samples\SCC Taiko Drums\Samples\taiko1-p.wav)
WARNING: Skipping duplicate sample: taiko1-m.wav (D:\Vault\Samples\SCC Taiko Drums\Samples\taiko1-m.wav)
WARNING: Skipping duplicate sample: taiko1-f1.wav (D:\Vault\Samples\SCC Taiko Drums\Samples\taiko1-f1.wav)
WARNING: Skipping duplicate sample: taiko1-f2.wav (D:\Vault\Samples\SCC Taiko Drums\Samples\taiko1-f2.wav)
Finished converting D:\Vault\Samples\SCC Taiko Drums\SCC Taiko Drums.sfz to multisample

Conversion Results:
  61 samples mapped from 67 regions

  101 SFZ opcodes were lost in translation:
    (67)  ampeg_release=5
    (11)  seq_position=1
    (11)  seq_position=2
    (3)  fil_type=lpf_1p
    (2)  seq_position=3
    (2)  fil_veltrack=9600
    (2)  cutoff=100
    (1)  amp_veltrack=100
    (1)  fil_veltrack=100
    (1)  cutoff=4500

  Suggested Bitwig sampler AHDSR settings:
    (67)  R = 5 s

Writing multisample D:\Vault\Samples\SCC Taiko Drums\SCC Taiko Drums.multisample
Finished writing multisample D:\Vault\Samples\SCC Taiko Drums\SCC Taiko Drums.multisample
```
